# -*- coding: utf-8 -*-
"""eng-219-056/2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tDeWUJj7kiP7mxZfpDb1n9mowQfq6pw
"""

def solve_second_order_de(r1, r2):
    # checking the type of roots
    if r1 == r2:
        yh = "(C1 + C2*x)e^(" + str(r1) + "x)"
    else:
        yh = "C1*e^(" + str(r1) + "x) + C2*e^(" + str(r2) + "x)"

    print("Homogeneous solution is:")
    print("y_h =", yh)

    # user enters the particular solution
    yp = input("Enter particular solution y_p: ")

    print("Particular solution is:")
    print("y_p =", yp)

    # final general solution
    print("General solution is:")
    print("y =", yh, "+", yp)


# main part
r1 = float(input("Enter first root: "))
r2 = float(input("Enter second root: "))

solve_second_order_de(r1, r2)